export const SUPABASE_URL = 'https://wtlzsfhhjmyegmdmwigh.supabase.co'
export const SUPABASE_ANON_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0bHpzZmhoam15ZWdtZG13aWdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2Nzg4MzcsImV4cCI6MjA4OTI1NDgzN30.irYXNTPEj2KBK1GyvbLJfxCukFjrhe8JE1fYWeIRvYc'
